Home 화면 5-issue
NBC-YouTube/Youtube pull request #11
Opened 2024-05-15 07:05 UTC by Sth-bear

api 요청부분은 viewmodel factory에서 test로 연결되어있습니다. 이후 원본이랑 연결하겠습니다. 

Popular, Category 양쪽 video 모두 video adapter를 사용합니다. 어떤 viewtype을 함께 명시하여 둘중 어디에 들어가는지 판단합니다. 

아이템 클릭처리는 fragment에서 하고있습니다. onclick 콜백이 해당 아이템을 가지고있습니다. 그대로  detail로 전송합니다. 

category list의 경우 옵저빙을 사용하여 api에서 받아온 리스트를 아이템으로 사용중입니다. 카테고리 특성상 onClick이 아닌, onItemSelected를 통해서 선택된 값으로 api를 요청하고있습니다.

2024-05-15 07:38 UTC, DoTheBestMayB requested changes

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/videmodels/CategoryViewModel.kt
categoryViewModel 또는 videosViewModel을 다른 Fragment와 공유하기 위한 것이 아니라면 한 개의 ViewModel에서 관리하는 것이 좋겠습니다.

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +    private fun category() {
함수 이름은 동사로 시작하는 것이 좋습니다.

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/adapters/VideoAdapter.kt
> +    }
두 Holder의 UI와 코드가 동일한데, 한 개의 ViewHolder로 통일해도 되지 않나요?

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/item_home_category.xml
> +    android:layout_height="match_parent">
height를 wrap_content로 변경하는 것이 안전하겠습니다.

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +                findNavController().navigate(action)
HomeFragment에서는 HomeFragmentAction을 사용해야 합니다.
이 코드가 실행되면 runtime Exception으로 앱이 죽지 않나요?

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +        videosViewModel.loadPopularVideos()
viewModel의 초기 값을 로딩하는 코드가 onViewCreated에 있으면, Fragment의 View만 파괴되고, 다시 View가 생성될 때마다 호출됩니다.
category 값이 짧은 시간 내에 변경되지는 않으므로 불필요한 호출이 되겠습니다.

또한 이 코드로 인해 다른 탭으로 이동 후 돌아왔을 때, 이전에 보던 카테고리가 아닌 카테고리1로 초기화됩니다.

2024-05-15 07:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/item_home_category.xml
> +        android:textSize="12dp"
textSize는 sp를 사용해야 합니다.

2024-05-15 07:56 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/videmodels/CategoryViewModel.kt
제 생각에는 videoViewModel의 경우 api로 받아오는 비디오만, category의 경우 category 아이템만 담당하기에 분리하는것이 이후 유지 보수에 좀 더 장점이 있지 않을까는 생각에 분리했습니다. 합치는것이 좀 더 좋은처리가 될까요?

2024-05-15 07:56 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/adapters/VideoAdapter.kt
> +    }
들어가는 binding의 대상이 달라서 따로뒀습니다. 그러면 binding의 대상을 어디서 지정하는게 좋은가요?

2024-05-15 07:56 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +                findNavController().navigate(action)
확인했습니다 반영되었습니다.

2024-05-15 07:56 UTC, Sth-bear commented on app/src/main/res/layout/item_home_category.xml
> +    android:layout_height="match_parent">
원본 크기를 fragment.xml에서 지정을해놓고, 이에 맞춰 match_parent를 했는데 반대로 fragment에서 wrap을 사용하고 여기서 크기를 지정하는게 더 좋을까요?

2024-05-15 07:56 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +        videosViewModel.loadPopularVideos()
popular은 새로고침이 따로 없기에 돌아올때마다 새로 불러오는것은 의도되었으나, 카테고리는 그렇지 않은 부분입니다. 카테고리를 받아오는 부분은 oncreate로 옮기는것이 좋다는 의견이실까요?

2024-05-15 07:59 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +        videosViewModel.loadPopularVideos()
1. 유튜브의 인기 동영상 목록이 사용자가 앱을 사용하는 짧은 시간 동안 업데이트 되지는 않을 것 같습니다.
2. 네 onCreate로 옮기는 게 좋겠습니다.

2024-05-15 08:35 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/videmodels/CategoryViewModel.kt
저는 분리했을 때의 장점이 무엇인지 떠오르지 않네요. 아직 발생하지 않은 추상적인 상황을 가정해서 코드를 작성하는 것은 지양하는 것이 좋다고 생각합니다.

2024-05-15 08:37 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/home/adapters/VideoAdapter.kt
> +    }
ItemHomeMostPopularBinding와 ItemHomeCategoryBinding의 xml 코드를 보면 UI가 동일하기 때문에 한 개의 ViewHolder로 관리해도 되겠습니다.

꼭 분리해야 하는 ViewHolder를 생각해보면 Channel이 되겠네요

2024-05-15 08:41 UTC, DoTheBestMayB commented on app/src/main/res/layout/item_home_category.xml
> +    android:layout_height="match_parent">
지금 코드로도 문제가 없으나, viewHolder가 필요한 크기만 차지하도록 설정하는 습관을 가지는 것이 좋습니다.
그렇지 않으면 예상하지 않은 UI 결과를 직면하게 됩니다.

https://dodobest.tistory.com/45

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/adapters/VideoAdapter.kt
> +    }
해당부분은 수정중에 있습니다. viewBinding이 아닌, findById를 사용한다면 두개를 합치는것이 가능했으나, ViewBinding을 통해서 하는방법을 찾고있습니다.

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/res/layout/item_home_category.xml
> +    android:layout_height="match_parent">
확인했습니다. 각각의 아이템 xml에도 dp포인트를 정확하게 명시하고 있기에 해당부분도 wrap으로 감싸는 방식으로 변경하였습니다.

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +        videosViewModel.loadPopularVideos()
네. 반영했습니다. 
확인결과 .load하는 부분을 모두 onCreate로 옮겼음에도 지속적으로 1번으로 가는 현상이 있었습니다. 
해당 adapter를 선언할때 상단부에서 선언한것이 아닌, lateinit var 를 통해서 하단부에서 adapter를 계속 다시 선언하는 문제도 함께 발견되었습니다. 해당 두 부분 모두 수정되었습니다.

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/res/layout/item_home_category.xml
> +        android:textSize="12dp"
반영되었습니다.

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/HomeFragment.kt
> +    private fun category() {
확인했습니다. 전체적으로 함수를 교체하였습니다. 
기존의 observe가 각 부분을 bind할때 있었으나, 카테고리, 리사이클러뷰의 observe를 한곳으로 모아서 선언했습니다. 이에 리사이클러뷰를 bind하던 3개의 함수를 하나로 축소시켰습니다.

2024-05-15 09:20 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/videmodels/CategoryViewModel.kt
담당하는 부분별로 쪼개두는것이 이후 처리가 쉽다는 생각이었습니다. 
해당부분은 VideoVideModel에 합병처리하였습니다.

2024-05-16 02:08 UTC, DoTheBestMayB approved these changes, later dismissed

2024-05-16 02:42 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/home/adapters/VideoAdapter.kt
> +    }
반영되었습니다. 두개를 하나의 함수로 동시에 처리하기 위해서 각 xml의 id를 동일하게 교체하였습니다. 
이에 holder에서 Id값을 통해 두 대상모두 동일한 값에 접근하도록 교체되었습니다. 이에 각 Holder가 하나로 통일되었습니다.

2024-05-16 02:47 UTC, DoTheBestMayB approved these changes, later dismissed

2024-05-16 08:59 UTC, Yejin-Byun submitted a review, later dismissed
스피너를 사용해 본 적이 없어서 어댑터 설정하는 부분 잘 봤습니다!

2024-05-16 12:16 UTC, merged