Feature/search
NBC-YouTube/Youtube pull request #13
Opened 2024-05-17 01:47 UTC by Yejin-Byun

2024-05-17 01:55 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/model/VideoEntity.kt
>   * @param channelTitle 채널이름
해당부분은 이전작업을 pull할때 겹치는 부분이 있었던걸로 보입니다. 확인후 수정이 된 부분인가요?

2024-05-17 01:55 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchFragment.kt
> +    }
onCreate를 오버라이드 하셨는데 작업이 없는 것 같습니다.

2024-05-17 01:55 UTC, Sth-bear commented on app/src/main/res/values/themes.xml
>      </style>
머지과정에서 생긴라인으로 보입니다. 삭제해주시면 될 것 같습니다.

2024-05-17 01:55 UTC, Sth-bear commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchViewModel.kt
> +                    )
들여쓰기가 너무 많이 들어간것 같습니다. 개인적으로는 map을 하는 함수를 아래에 private fun 으로 선언하시면 줄일 수 있지 않을까 합니다.

2024-05-17 08:25 UTC, Sth-bear approved these changes, later dismissed

2024-05-17 11:20 UTC, Sth-bear approved these changes, later dismissed

2024-05-17 13:56 UTC, DoTheBestMayB requested changes

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchFragment.kt
> +        baseButtonColor = binding.kidsBtn.backgroundTintList
키즈 필터를 눌렀다는 "상태"는 ViewModel에서 관리하는 것이 좋겠습니다.

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchFragment.kt
> +            viewModel.loadSearchVideos(query, "moderate")
SafeSearchType을 String으로 관리하는 것보다 Enum class로 관리하는 것이 좋겠습니다.

Q. Enum으로 관리하면 장점이 무엇일까요?

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchFragment.kt
> +    }
같은 Key 값을 여러 곳에서 동시에 관리하는 것은 위험합니다. 만약 DetailFragment에서 Key 값을 변경할 경우, SearchFragment의 Key 값과 일치하지 않아, Observing으로 데이터가 수신이 되지 않고, 이러한 논리적 오류를 찾기란 매우 어렵습니다.

따라서 DetailFragment의 Key값을 사용하는 것이 좋겠습니다.

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchFragment.kt
> +                }
DetailFragment에서는 좋아요 여부를 Boolean 값으로 전달하도록 변경되었는데, 이 부분 반영이 누락된 것 같습니다!

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/model/VideoInfoWithLiked.kt
> +    fun likedToVideoEntity() : VideoInfo {
함수 명을 `likedToVideoInfo`로 변경해서 실제 반환하는 클래스와 일치시키면 좋겠습니다.

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchViewModel.kt
> +    }
ViewModel 뿐만 아니라 Repository를 통해 Room에도 반영해주셔야 합니다!

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchViewModel.kt
> +                val videos = repository.getSearchVideo(query, safeSearchType)
getSearchVideo 함수의 반환 값은 VideoInfo 입니다!

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchAdapter.kt
> +                .into(binding.searchLikeBtn)
서버로부터 이미지를 불러오는 것이 아니기 때문에, setImageResource 함수를 사용하면 좋겠습니다.

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/java/com/nbc/youtube/presentation/search/SearchAdapter.kt
> +                return oldItem.thumbnail == newItem.thumbnail
thumbnail 보다는 video의 고유 id로 비교하는 것이 좋겠습니다!

유튜브 플랫폼의 특성을 생각해보면, 영상을 올린 사람이 영상의 썸네일을 변경하면 썸네일 주솟값이 변경될 수 있기 때문에 불변인 id 값으로 비교하는 것이 안전하겠습니다.

2024-05-17 13:56 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_search.xml
> +        android:layout_height="610dp"
특별한 경우가 아니라면 width와 height은 constraint를 이용해 0dp로 지정하는 것이 좋겠습니다.
preview에서 화면이 세로로 더 긴 기기로 변경하면 RecyclerView가 중간에 붕 뜨게 됩니다.

![image](https://github.com/NBC-YouTube/Youtube/assets/48354989/b0a2a309-cdc2-4455-ad22-898064fdadb9)

2024-05-21 00:10 UTC, DoTheBestMayB approved these changes

2024-05-21 00:10 UTC, merged